# Generated by Django 5.2 on 2025-04-09 19:27

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ReturnReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Причина возврата')),
                ('category', models.CharField(choices=[('unopened', 'Невскрытый товар'), ('opened', 'Вскрытый товар')], max_length=10, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Причина возврата',
                'verbose_name_plural': 'Причины возврата',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=core.models.generate_order_id, max_length=20, unique=True, verbose_name='ID заказа')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('payment_status', models.CharField(choices=[('prepaid', 'Предоплачен'), ('postpaid', 'Постоплата')], default='prepaid', max_length=10, verbose_name='Статус оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает получения'), ('delivered', 'Выдан'), ('returned', 'Возвращен'), ('cancelled', 'Аннулирован')], default='pending', max_length=10, verbose_name='Статус заказа')),
                ('is_under_inspection', models.BooleanField(default=False, verbose_name='На проверке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата приемки')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='PickupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_package', models.BooleanField(default=False, verbose_name='Добавить пакет')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_sessions', to='core.customer', verbose_name='Клиент')),
                ('orders', models.ManyToManyField(related_name='pickup_sessions', to='core.order', verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'Сессия выдачи',
                'verbose_name_plural': 'Сессии выдачи',
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата возврата')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_info', to='core.order', verbose_name='Заказ')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.returnreason', verbose_name='Причина возврата')),
            ],
            options={
                'verbose_name': 'Возврат заказа',
                'verbose_name_plural': 'Возвраты заказов',
            },
        ),
        migrations.CreateModel(
            name='StorageCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер ячейки')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Занята')),
                ('current_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_cells', to='core.customer', verbose_name='Текущий клиент')),
            ],
            options={
                'verbose_name': 'Ячейка хранения',
                'verbose_name_plural': 'Ячейки хранения',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='storage_cell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.storagecell', verbose_name='Ячейка хранения'),
        ),
    ]
