# Generated by Django 5.2 on 2025-04-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='received_at',
            new_name='reception_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_under_inspection',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_picked_up',
            field=models.BooleanField(default=False, verbose_name='Выдан'),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='order',
            name='reception_status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('received', 'Принят'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус приемки'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='pickupsession',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='pickupsession',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='storage_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.storagecell', verbose_name='Ячейка хранения'),
        ),
    ]
