# Generated by Django 5.2 on 2025-04-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_delivered_at_order_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marked_for_return',
            field=models.BooleanField(default=False, verbose_name='Отмечен для возврата'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания к возврату'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_reason_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID причины возврата'),
        ),
    ]
