# Generated by Django 5.2 on 2025-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_storagecell_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupsession',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
